# Generated by Django 5.1.6 on 2025-03-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pricingplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
