# Generated by Django 5.1.6 on 2025-03-16 16:14

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the plan name (e.g., Basic, Pro, Enterprise)', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price (e.g., 19.99)', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Short description of the plan')),
                ('features', models.TextField(help_text='List of features (separated by commas)')),
                ('icon', models.ImageField(blank=True, help_text='Upload an icon for this plan', null=True, upload_to=home.models.pricing_plan_icon_upload)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Active plans will be displayed on the website', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['price'],
            },
        ),
    ]
