# Generated by Django 5.1.6 on 2025-03-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pricingplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['order'], 'verbose_name': 'Pricing Plan', 'verbose_name_plural': 'Pricing Plans'},
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
