# Generated by Django 5.1.6 on 2025-03-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_faq_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('Panding', 'Panding'), ('Solved', 'Solved'), ('Archive', 'Archive')], default='Panding', max_length=10),
        ),
    ]
