# Generated by Django 5.1.6 on 2025-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_faq_email_alter_faq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
