# Generated by Django 5.1.6 on 2025-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_faq_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
