# Generated by Django 5.1.6 on 2025-03-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_notify_faq_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
