# Generated by Django 5.1.6 on 2025-03-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfaauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfasecret',
            name='qr_code_image',
            field=models.FileField(blank=True, null=True, upload_to='mfa_qr_codes/'),
        ),
    ]
