# Generated by Django 5.1.6 on 2025-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfaauth', '0002_alter_mfasecret_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfasecret',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='mfa_qr_codes/'),
        ),
    ]
