# Generated by Django 5.1.6 on 2025-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfaauth', '0003_alter_mfasecret_qr_code_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfasecret',
            name='user',
        ),
        migrations.AddField(
            model_name='mfasecret',
            name='email',
            field=models.EmailField(default='hak997327@gmail.com', max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='mfasecret',
            name='issuer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
