# Generated by Django 5.1.6 on 2025-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfaauth', '0004_remove_mfasecret_user_mfasecret_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfasecret',
            name='email',
            field=models.EmailField(blank=True, default='hak997327@gmail.com', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='mfasecret',
            name='secret',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
