# Generated by Django 5.1.6 on 2025-03-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfaauth', '0005_alter_mfasecret_email_alter_mfasecret_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfasecret',
            name='issuer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
