# Generated by Django 5.1.6 on 2025-03-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfaauth', '0006_alter_mfasecret_issuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfasecret',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=70, unique=True),
        ),
    ]
