# Generated by Django 5.1.6 on 2025-03-11 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfaauth', '0007_alter_mfasecret_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfasecret',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
